name: fc_path_util
description: Helper methods for dart `path` package.
version: 1.0.1
repository: https://github.com/flutter-cavalry/fc_path_util

environment:
  sdk: ">=2.19.5 <3.0.0"

dependencies:
  path: ^1.8.2

dev_dependencies:
  lints: ^2.0.0
  test: ^1.21.0
