name: fc_path_util
description: Helper methods for dart `path` package.
version: 1.1.0
repository: https://github.com/flutter-cavalry/fc_path_util

environment:
  sdk: ">=2.19.5 <3.0.0"

dev_dependencies:
  lints: ^4.0.0
  test: ^1.21.0
